### ISSUE TITLE
Shortcode Multiple - Radio issues

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/BBT_FW#10]
Daca dai ai radio in multiple -> selectezi valoarea / o ia pe cea default corect -> dai add more -> primul pierde valoarea, al 2-lea nu ia defaultul, dai valoarea e ok, te duci back la primul si dai iar valoarea, dispare la al 2-lea.

**Comment by andreimarin90** [comment]
Acelasi behavior si la select. Cred ca e id-based sau ceva

**Comment by toleabivol** [comment]
@andreimarin90 vezi cu ultimul update la fw , daca tot ai issue dami exemplu cum ai construit meta-boxes.php
