### ISSUE TITLE
Updated Js and Css Enque names

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/BBT_FW#2]
Am schimbat din options.js si screen.css in bbt.js si bbt.css. Per toate projectele sa schimbam sa fie asa denumite fisierele respective. (options si screen chiar nu make sense). @toleabivol  @leonidrm

**Comment by andreimarin90** [comment]
Eu am rezolvat Wordie, mai raman BA, Santi, VSD, @toleabivol fa sub...stuff si la VSD te rog.

**Comment by toleabivol** [comment]
Si sa schimb default sa fie bbt.js si bbt.css main files la enqueue (se adauga ultimele) ?
Altfel trebuie sa faci :

    BBT_ENQUEUE::$main_js = 'bbt.js';
    BBT_ENQUEUE::$main_css = 'bbt.css';

Daca da fac update la FW si va afecta toate temele cu enqueue automatizat , odata ce updatati fw tre sa fie si redenumite fisierele.

**Comment by toleabivol** [comment]
Ah vad ca ai facut asta deja , bine updatam la toate temele atunci

**Comment by toleabivol** [comment]
BA & Santi done , la VSD tre de reparat putin repo apoi facem restu si issue closed
