### ISSUE TITLE
No style

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/BBT_FW#3]
Nu stiu ce ai facut dar nu mai avem styling.

**Comment by toleabivol** [comment]
Adica ? care styling a disparut ?

**Comment by andreimarin90** [comment]
Scuze! Toxo style

**Comment by toleabivol** [comment]
Hmmm , la mine merge bine . Screen + consola pls

**Comment by andreimarin90** [comment]
Solved. Lipsea toco folder din tema.
