### ISSUE TITLE
Add Multiple pentru meta box where possible (text,textarea,checkbox,image)

### ISSUE THREAD

**Issue by andreimarin90** [andreimarin90/BBT_FW#9]
https://github.com/bainternet/My-Meta-Box/blob/master/class-usage-demo.php

**Comment by toleabivol** [comment]
'input_fields'   => array(            			// list of meta fields 
					'repeatertest'	=>	array(
						'name'	=>	'Repeater Test',
						'type'	=>	'repeater',
						'fields'	=>	array(
							'slider_r'=>array(
								'name'=>_x('Revolution R Slider alias (choose header with slider type) ','meta boxes','bonappetit'),
								'type'=>'text'
							),
							'header_r'=>array(
								'name'=>'Header Image R (paralaxed)',
								'type'=>'image'
							),
						)
					),
    ...

**Comment by andreimarin90** [comment]
Notice: Undefined index: type in /Volumes/Work/wd/localhost/wp-content/themes/C3/bbt_framework/extensions/meta-box-class/my-meta-box-class.php on line 445

Notice: Undefined index: type in /Volumes/Work/wd/localhost/wp-content/themes/C3/bbt_framework/extensions/meta-box-class/my-meta-box-class.php on line 446

Warning: call_user_func() expects parameter 1 to be a valid callback, class "AT_Meta_Box" does not have a method "show_field_" in /Volumes/Work/wd/localhost/wp-content/themes/C3/bbt_framework/extensions/meta-box-class/my-meta-box-class.php on line 446

**Comment by andreimarin90** [comment]
http://bigbangthemes.net/C3_WP/wp-admin/post.php?post=623&action=edit @toleabivol

**Comment by toleabivol** [comment]
@andreimarin90 nu vad in linkul asta eroarea , sau ai scos multiple ca e buggy ?

**Comment by toleabivol** [comment]
Aparea cind repetear era folosit dupa un input simplu in acelasi metabox
